CREATE TABLE CROP_ANALYSES (
  ID NUMBER PRIMARY KEY,
  CROP_NAME VARCHAR2(100) NOT NULL,
  STATUS VARCHAR2(20) NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  HEALTH_SCORE NUMBER(3)
);

CREATE SEQUENCE CROP_ANALYSES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CROP_ANALYSES_BI
BEFORE INSERT ON CROP_ANALYSES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT CROP_ANALYSES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

INSERT INTO CROP_ANALYSES (CROP_NAME, STATUS, CREATED_AT, HEALTH_SCORE)
VALUES ('Tomato', 'Healthy', SYSDATE - 1, 92);

INSERT INTO CROP_ANALYSES (CROP_NAME, STATUS, CREATED_AT, HEALTH_SCORE)
VALUES ('Potato', 'Diseased', SYSDATE - 2, 48);

INSERT INTO CROP_ANALYSES (CROP_NAME, STATUS, CREATED_AT, HEALTH_SCORE)
VALUES ('Wheat', 'Healthy', SYSDATE - 3, 86);

INSERT INTO CROP_ANALYSES (CROP_NAME, STATUS, CREATED_AT, HEALTH_SCORE)
VALUES ('Rice', 'Diseased', SYSDATE - 4, 55);

INSERT INTO CROP_ANALYSES (CROP_NAME, STATUS, CREATED_AT, HEALTH_SCORE)
VALUES ('Maize', 'Healthy', SYSDATE - 5, 78);

COMMIT;
